spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: order-details
        order-details-input-channel:
          destination: order-details
        india-order-channel:
          destination: india-order-details
        international-order-channel:
          destination: international-order-details
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              schema.registry.url: http://localhost:8081
              processing.guarantee: exactly_once
        
              