spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: order-input-topic
        order-output-channel:
          destination: order-output-topic
      kafka:
        binder:
          brokers:  localhost:9092
          configuration:
            schema.registry.url: http://localhost:8081            
       


