spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: order-details
        customer-input-channel:
          destination: customer-details       
      kafka:
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              commit.interval.ms: 5000
              state.dir: order-customer-store
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              
          

