global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - kafka1:8080 #Change as per your config
      - kafka3:8080 #Change as per your config